apiVersion: v1
data:
  mongo-server: mongodb-service
kind: ConfigMap
metadata:
  name: mongo-cm-5hd5d2f2d5
  namespace: develop
---
apiVersion: v1
data:
  mongo-pass: Z2FuZG9u
  mongo-user: a2xpcnNjY2Vx
kind: Secret
metadata:
  name: mongodb-secret
  namespace: develop
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-express
  name: mongodb-express-service
  namespace: develop
spec:
  ports:
  - name: mongo-express
    nodePort: 30000
    port: 8081
    targetPort: 8081
  selector:
    app: mongo-express
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb-service
  namespace: develop
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Mi
  hostPath:
    path: /data/db
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
  namespace: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-user
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-pass
              name: mongodb-secret
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              key: mongo-server
              name: mongo-cm-5hd5d2f2d5
        image: mongo-express
        name: mongo-express
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: develop
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb-service
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongo-user
              name: mongodb-secret
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongo-pass
              name: mongodb-secret
        image: mongo
        imagePullPolicy: Never
        name: mongodb-container
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - mountPath: /data/db
          name: data
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
