apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - image: mongo-express
        name: mongo-express
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-user
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-pass
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
               name: mongo-cm
               key: mongo-server

--- 

apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
  labels:
    app: mongo-express
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    name: mongo-express
    nodePort: 30000
  selector:
    app: mongo-express